const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
assert.equal(manifest.manifest_version, 3);
assert.equal(manifest.version, '0.1.5');
assert.equal(manifest.action.default_popup, 'src/popup.html');
assert.ok(manifest.permissions.includes('activeTab'));
assert.ok(manifest.permissions.includes('scripting'));
assert.ok(manifest.permissions.includes('downloads'));
assert.ok(fs.existsSync(path.join(root, 'src/background.js')));
assert.ok(fs.existsSync(path.join(root, 'src/popup.html')));
assert.ok(fs.existsSync(path.join(root, 'src/popup.css')));
assert.ok(fs.existsSync(path.join(root, 'src/popup.js')));
const popup = fs.readFileSync(path.join(root, 'src/popup.html'), 'utf8');
const popupScript = fs.readFileSync(path.join(root, 'src/popup.js'), 'utf8');
assert.match(popup, /launch-report-button/);
assert.match(popup, /run-report-button/);
assert.match(popup, /capture-table-button/);
assert.match(popup, /copy-captures-button/);
assert.match(popup, /export-captures-button/);
assert.match(popup, /start-date/);
assert.match(popup, /end-date/);
assert.match(popupScript, /customreport\.aspx/);
assert.match(popupScript, /1847/);
assert.match(popupScript, /title="Reports"/);
assert.match(popup, /Choose dates here/);
assert.match(popupScript, /start-date-input-simple/);
assert.match(popupScript, /end-date-input-simple/);
assert.match(popupScript, /Backspace/);
assert.match(popupScript, /capturesAsTsv/);
assert.match(popupScript, /navigator\.clipboard/);
assert.ok(fs.existsSync(path.join(root, 'design/tokens.css')));
console.log('Cocotivity eLead extension smoke test: passed');
